Numpy Array

Estructura central de Numpy
Representa datos de una manera estructurada
Indexado
Acceso a uno o muchos elementos

In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)

type(arr)

numpy.ndarray

In [5]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

INDEXING

In [7]:
arr[0]

arr[0] + arr[5]

7

In [10]:
matriz[0]
# para acceder a los indices en las matrices se separa asi -> filas,columnas
matriz[0, 2]

3

SLICING

In [13]:
arr[1:5]  # si se coloca solo :6 busca desde la posicion inicial hasta la indicada, si se hace 2: inicia desde la posicion 2 y llega hasta la ultima
arr[::3]  # Revisa toda la cadena y trae todos los valores pero de 3 en 3
arr[-1]  # Obtiene el ultimo valor de la lista

array([2, 3, 4, 5])

In [16]:
matriz[1:]  # obtiene desde la fila 1 en adelante
matriz[1:, 0:2]  # obtiene las filas desde la 1 y las columnas desde la 0 hasta la 2

array([[4, 5],
       [7, 8]])