In [11]:
import numpy as np

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10) #crea un listado con los numeros del 0 a 10
np.arange(0,20,2) #lista los numeros de 2 en 2 hasta el 20

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.zeros(3) #crea listas o matrices con 0s
np.ones((3,3)) #crea una matriz 3x3 de 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,10, 5) #obtiene 5 datos del 0 al 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.eye(4) #crea la matriz con 1 en diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand() #genera numeros aleatorios

np.random.rand(4,4) #genera una matriz 4x4 de valores aleatorios

np.random.randint(1,100, (10,10)) #crea una matriz 10x10 de valores enteros aleatorios

array([[75, 23, 24,  6, 93, 76, 84,  3, 99, 76],
       [80, 57,  5, 97, 41, 17, 63,  1, 12, 62],
       [97, 68, 75, 20, 97,  7, 90, 26, 75, 27],
       [14, 63, 60, 43, 67, 63, 30, 23, 56, 30],
       [13, 43,  4, 57, 85, 86, 21, 82, 92, 15],
       [34, 22, 72, 37, 52, 24, 76, 91, 14, 42],
       [55, 49, 99, 39, 50, 73, 30, 83, 45, 11],
       [66, 47, 96, 85, 82, 91, 61, 12,  9, 78],
       [31, 14, 26, 45, 57, 67, 10, 29,  7,  9],
       [ 6, 89, 41, 16, 77, 49, 65, 77,  5, 35]])