In [2]:
import numpy as np

In [4]:
scalar = np.array(45)
print(scalar)
scalar.ndim

45


0

In [5]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [6]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 6, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 6, 9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [3 6 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [3 6 9]]]


3

## agregar o eliminar dimensiones

In [10]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
expand = np.expand_dims(np.array([1,2,3]), axis=0) #Axis=0 se refiere a filas y axis=1 significa columnas, con esto se expande una sola dimension
print(expand)

[[1 2 3]]


In [17]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector) #reduce la cantidad de dimensiones a la cantidad necesaria para representar el valor
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
