In [46]:
import numpy as np

In [47]:
arr = np.random.randint(1,20, 10)
matriz = arr.reshape(2,5)

In [48]:
arr.ptp() #obtiene la diferencia entre el valor mayor y el valor menor dentro del array

16

In [49]:
matriz.ptp(0) #obtiene la diferencia entre el valor mas alto y mas bajo de las columnas

array([14,  4,  1, 13,  2])

In [50]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [51]:
np.concatenate((a,b), axis=1) #concatena los valores de los arreglos en uno solo

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
a.T #obtiene la matriz transpuesta

array([[1, 3],
       [2, 4]])

## OBTENER MAXIMOS Y MINIMOS

In [53]:
print(arr)
arr.max() #valor maximo del array



[19  3 19 19  4  5  7 18  6  6]


19

In [54]:
print(matriz)
matriz.max() #valor maximo de la matriz

matriz.max(0) #si se coloca 1 obtiene los valores maximos por fila, si se coloca 0 los obtiene por columna

[[19  3 19 19  4]
 [ 5  7 18  6  6]]


array([19,  7, 19, 19,  6])

In [55]:
arr.argmax() #obtiene el indice de donde se encuentra nuestro valor mayor dentro del array

0

In [56]:
matriz.argmax() #obtiene el indice en el que se encuentra el mayor valor dentro de la matriz
matriz.argmax(0) #obtiene el indice en filas(1) o en columnas (0)

array([0, 1, 0, 0, 1], dtype=int64)

DE IGUAL FORMA FUNCIONA PARA HALLAR LOS VALORES MINIMOS QUE SE ENCUENTRAN DENTRO DE LOS ARREGLOS

## HERRAMIENTAS PARA ESTADISTICA

In [57]:
np.percentile(arr, 50) #obtiene el percentil que se encuentra en la mitad del array

6.5

In [58]:
arr.sort() #ordena los valores de menor a mayor
arr

array([ 3,  4,  5,  6,  6,  7, 18, 19, 19, 19])

In [59]:
np.median(arr) #obtiene la mediana del arreglo, funciona igual para la matriz np.median(matriz,0)

6.5

In [60]:
np.std(arr) #obtiene la desviacion estandar

6.740919818541086

In [61]:
np.var(arr) #Obtiene la varianza

45.44

In [62]:
np.mean(arr) #Obtiene la media(promedio) del arreglo

10.6