In [1]:
import numpy as np

In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [4]:
lista * 2 #Duplica los valores de la lista

[1, 2, 3, 1, 2, 3]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()

## OPERACIONES

In [6]:
arr * 2 #si se crea la lista con numpy esto si permite multiplicar cada valor de la lista por 2 y no duplicar la lista

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
1 / arr

C:\Users\Mario\AppData\Local\Temp\ipykernel_2144\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [10]:
arr + arr2 #Tambien permite operaciones entre arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

AHORA CON MATRICES

In [13]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz


In [14]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.matmul(matriz,matriz2.T) #Obtiene el producto punto de las matrices. Recordar que esto se hace sobre la matriz transpuesta.

array([[ 30,  80],
       [ 80, 255]])

In [17]:
matriz @ matriz2.T #Otra forma de hacer el producto punto.

array([[ 30,  80],
       [ 80, 255]])